# Site settings
title: Développeur web Magento e-commerce à Nantes / Amiens - Création de sites internet - laurentlepee.com
email: contact@laurentlepee.com
description: > # this means to ignore newlines until "baseurl:"
  Développeur Magento à Nantes, je crée des sites internet de vente en ligne e-commerce avec la solution Magento.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.laurentlepee.com" # the base hostname & protocol for your site
twitter_username: laurentlepee
github_username:  laurentlepee
linkedin_username:  laurentlepee
viadeo_username:  laurent.lepee 

# Build settings
markdown: kramdown

# Jekyll plugin
gems: [jekyll-seo-tag, jekyll-sitemap]

# Jekyll seo tag
twitter:
  username: laurentlepee
#google_site_verification: